// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXFJGYrvbOaPrNrF705ZIusJtCVQ0PzXA',
    appId: '1:756772827807:web:4b8592da640c2c88caa8aa',
    messagingSenderId: '756772827807',
    projectId: 'rumiroutine',
    authDomain: 'rumiroutine.firebaseapp.com',
    storageBucket: 'rumiroutine.firebasestorage.app',
    measurementId: 'G-15SL5T36G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3-L58RIxwu8cSA0tmyJh9XZ1nB95OI_E',
    appId: '1:756772827807:android:7c70e784b790a58bcaa8aa',
    messagingSenderId: '756772827807',
    projectId: 'rumiroutine',
    storageBucket: 'rumiroutine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA09wCoH7Htiedh0xWqqEpYET50zYFKfe4',
    appId: '1:756772827807:ios:d0f975a48750347fcaa8aa',
    messagingSenderId: '756772827807',
    projectId: 'rumiroutine',
    storageBucket: 'rumiroutine.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA09wCoH7Htiedh0xWqqEpYET50zYFKfe4',
    appId: '1:756772827807:ios:d0f975a48750347fcaa8aa',
    messagingSenderId: '756772827807',
    projectId: 'rumiroutine',
    storageBucket: 'rumiroutine.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXFJGYrvbOaPrNrF705ZIusJtCVQ0PzXA',
    appId: '1:756772827807:web:eadd8b2e62d040c8caa8aa',
    messagingSenderId: '756772827807',
    projectId: 'rumiroutine',
    authDomain: 'rumiroutine.firebaseapp.com',
    storageBucket: 'rumiroutine.firebasestorage.app',
    measurementId: 'G-3YLTNTV4BP',
  );
}
